### ISSUE TITLE
Corrected university name

### ISSUE THREAD

**Issue by anita0711** [education/GitHubGraduation-2021#10384]
I had submitted my PR earlier which was within the first 5K requests, and I had received a comment that I will get the swag.
After watching the grad walk, I realized there was a mistake in my university name and hence I corrected the same with a new PR. I'm curious to know will I still get the swag or not since my first accepted PR was in the first 5K requests?

**Comment by RupomChowdhury** [comment]
Nothing related to swag.. if you received the comment about getting swag from your first accepted PR. You'll get the swag. But they'll not accept your new PR.  Suppose they accept your new PR, but the problem is your new PR will not visible in the yearbook. So you cannot correct/fix your university name in the yearbook. 😢

**Comment by Rajat-Jain29** [comment]
Did you know when will SWAG will delivered?

**Comment by RupomChowdhury** [comment]
@Rajat-Jain29 they have stock right now. hopefully, end/mid of this month.
