### ISSUE TITLE
swag pack will not coming! change my mind

### ISSUE THREAD

**Issue by Lynicis** [education/GitHubGraduation-2021#10422]
change my mind but u cant this.

**Comment by elisemoe** [comment]
I'm not sure I can change your mind but I promise we're still working on swag 💖  We've had to make a few design changes and work with the printer to get the cards to the level we want to share with all of you. I'll update the repo as soon as I've seen the physical cards printed and heading to shipping!

**Comment by Lynicis** [comment]
u said and u still didn't update readme. why?

**Comment by shivang17** [comment]
@Lynicis : She said the update to README would happen once the physical printed cards will be headed to shipping. Please put your foot in Github's shoes and see how overwhelming it is to do such event and do everything for free. Have patience!

**Comment by manoj997** [comment]
@amashi996 @Bavanraj-5

**Comment by manoj997** [comment]
@elisemoe any updates?

CC: @juanpflores

**Comment by manoj997** [comment]
Hi @elisemoe ,

Please be kind enough to understand that due to COVID-19 pandemic, most of us did not have a physical convocation/graduation ceremony. The only hope we had was github virtual graduation and the swag kit. It would be really nice of you to hurry up the process and have the swags to all of us who are eligible ASAP. It has been a few months now and we have not heard anything. We're not sure whether the swags are given or not. 

Hope this comment finds you!

/Manoj

**Comment by elisemoe** [comment]
I'll continue to update the readme as the swag progresses through production 💚 We're close to shipping!

**Comment by manoj997** [comment]
@elisemoe Thank you very much for your update! :) <3

**Comment by Darkshadow9799** [comment]
@elisemoe  any updates on swag shipping?
