### ISSUE TITLE
Name not showing in yearbook

### ISSUE THREAD

**Issue by munizcodr** [education/GitHubGraduation-2021#9883]
Hi Sir,
My name is not showing on the yearbook page whether I have pulled the request successfully.

**Comment by munizcodr** [comment]
Hi Sir,
My name is not showing on the yearbook page whether I have pulled the request successfully.

**Comment by munizcodr** [comment]
Please do needful in this matter.

**Comment by adityakumar48** [comment]
@munizcodr 
Hey , Its Just Too Many . Just Clone this Repository on  your Local System machine and Check it

git clone https://github.com/education/GitHubGraduation-2021

**Comment by Ruqhaiya** [comment]
Hey @munizcodr ,
When you are inside the repo https://github.com/education/GitHubGraduation-2021, you can see a button on the top right probably "Go to file", click that button and type your file name over there. 

If your file pops up, then congratulations you are in the class of 2021, otherwise, you might wanna check your pull request and see the bot's response, if there is an issue with your pull request, bots will provide a review soon. 

Hope this helps!

**Comment by munizcodr** [comment]
Thank you very much Sir/Mam! For help me.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
