### ISSUE TITLE
Can’t  find my name in the _data folder

### ISSUE THREAD

**Issue by Abhi-Dey** [education/GitHubGraduation-2021#9923]

**Comment by Batishavo** [comment]
me too, and try to create one and i can't

**Comment by adityakumar48** [comment]
There are Two Ways :

1. -  Its Just Too Many . Just Clone this Repository on your Local System machine and Check it

git clone https://github.com/education/GitHubGraduation-2021 

2. When you are inside the repo https://github.com/education/GitHubGraduation-2021, you can see a button on the top right probably "Go to file", click that button and type your file name over there.

If your file pops up, then congratulations you are in the class of 2021, otherwise, you might wanna check your pull request and see the bot's response, if there is an issue with your pull request, bots will provide a review soon.

Hope Its Helpful

**Comment by Abhi-Dey** [comment]
@Batishavo still can't find it!

**Comment by bhawesh2002** [comment]
@Abhi-Dey  your pull request might not be merged in the repo.

**Comment by pranjay-poddar** [comment]
it's because your pull request is not merged in the main branch.

**Comment by praveenscience** [comment]
What's your PR number folks?

**Comment by Sanan4li** [comment]
If you have pulled a request and it has been merged then you will see your folder. If you have pulled a request and it's still open check the bot comment on your PR.
For swag, your PR must be merged in the first 5000 PRs. I think they have completed the 5000 PRs and swag will not be shipped to new PRs.
